### PR TITLE
fix: Switch to remote environment pipelines

### PR DESCRIPTION
**Pull request by msvticket**
This repo is intended for a remote cluster and thus it should use the appropriate lighthouse config.

Since `jx admin log` can't access a remote cluster  the release pipeline just hangs anyway.

### CODE REVIEW

**Review by ankitm123 — APPROVED** [review]

**Comment by ankitm123** [comment]
Isn't this also used for on prem clusters?

**Comment by msvticket** [comment]
It shouldn't be. The about says "Jenkins X 3.x GitOps repository for a vanilla Kubernetes remote production or staging cluster "
It's rather jx3-gitops-repositories/jx3-kubernetes that should be used for on prem, right?

**Comment by ankitm123** [comment]
Yes, ur right. The description of the repo confused me, removed my comments right after posting, should have just edited ...

**Pull request merged**
